name: petjoo
description: A new Flutter project.
publish_to: 'none'
version: 1.3.6+36
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #teska
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  dio: ^4.0.6
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.8
  firebase_messaging: ^13.0.1
  firebase_dynamic_links: ^4.3.8
  firebase_analytics: ^9.3.6
  easy_localization: ^3.0.1
  url_launcher:
  image_picker: ^0.8.5+3
  stylish_bottom_bar: ^0.1.5
  path_provider: ^2.0.11
  badges: ^2.0.3
  share_plus: ^4.1.0
  calendar_appbar: ^0.0.6
  table_calendar: ^3.0.7
  font_awesome_flutter: ^10.2.1
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  map_launcher: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  flutter_gen:

  # flutter_native_splash: ^2.2.7
  
# flutter_native_splash:
#   color: "#FAEE4A"
#   image: assets/images/logo.png
#   android: true
#   ios: true
#   android_12: 
#     color: "#FAEE4A"
#     image: assets/images/logo.png
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/docs/
    - assets/images/
    - assets/translations/