name: petjoo
description: A new Flutter project.
publish_to: 'none'
version: 1.2.3+30
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartx: ^1.0.0
  intl: ^0.17.0
  sprintf: ^6.0.0
  async: ^2.8.2
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.0.0-dev.9
  firebase_dynamic_links: ^4.3.1
  google_sign_in: ^5.3.0
  sign_in_with_apple: ^3.3.0
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  package_info_plus: ^1.3.1
  sign_button: ^2.0.2
  share_plus: ^4.0.4
  crypto: ^3.0.1
  font_awesome_flutter: ^10.1.0
  flutter_image_compress: ^1.1.0
  table_calendar: ^3.0.6
  material_design_icons_flutter: ^5.0.6996
  cupertino_icons: ^1.0.2
  #teska
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.3.1
  firebase_messaging: ^11.4.4
  url_launcher:
  bubble_bottom_bar: ^2.0.0
  image_picker: ^0.8.5+3
  stylish_bottom_bar: ^0.1.4
  path_provider: ^2.0.11
  badges: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  flutter_native_splash: ^2.2.7
flutter_native_splash:
  color: "#FAEE4A"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12: 
    color: "#FAEE4A"
    image: assets/images/logo.png
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/docs/
    - assets/images/