// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwXq8eUTGndkSxs9nUgLMogLVixE2CBU',
    appId: '1:359336619289:android:f61988dff8f6afd417e988',
    messagingSenderId: '359336619289',
    projectId: 'petjoo-129db',
    storageBucket: 'petjoo-129db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbrcSXIS6TBFPQWBzuJmcD5uo-Hwl6jU',
    appId: '1:359336619289:ios:a38893aa0599c92117e988',
    messagingSenderId: '359336619289',
    projectId: 'petjoo-129db',
    storageBucket: 'petjoo-129db.appspot.com',
    androidClientId: '359336619289-meslgbqbqvi6va3prb03a41br8jsote1.apps.googleusercontent.com',
    iosClientId: '359336619289-q9tu9pg071r59f5v39usn2co4f4cs62j.apps.googleusercontent.com',
    iosBundleId: 'com.petjoo.ios',
  );
}
